### ISSUE TITLE
Reconsider design of feedback loop

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-design-system#471]
GDS have updated the feedback loop for GOV.UK, as they felt it was more of an interface.

The text links are now buttons.

<img width="1012" alt="Screenshot 2020-10-26 at 08 48 59" src="https://user-images.githubusercontent.com/10854265/97151933-1ae22d00-1768-11eb-8114-81ad67035c9f.png">

https://ukgovernmentdigital.slack.com/archives/C062GAGLW/p1603445620233000

Please can you consider whether we should do this?

**Comment by jkmnch** [comment]
Since the updated [feedback loop component](https://components.publishing.service.gov.uk/component-guide/feedback) is fairly new, we will not look at implementing a similar design on the WMN website until further research has been done by GOV.UK to prove that this new component is more accessible than the previous design (text links).

Also, adding buttons into the component increases the size on desktop and most notably on mobile, where on the smallest viewport it takes up half of the screen space which is not ideal. On pages where there is minimal body content, the visual attention of the new feedback component increases, distracting users from the main actions within the body content.

Hannah Jump (Content Designer for GDS) has already raised an issue with the new component:
"I've seen some feedback from people using the postcode checker - [gov.uk/find-coronavirus-local-restrictions](https://www.gov.uk/find-coronavirus-local-restrictions) which suggests that on the 'results page' (once they type in a postcode) they're not noticing the information for their result, but just the feedback banner. This suggests it's more prominent than the content and distracting from the main call to action on the page. Although this is assumptions on feedback and not anything we've seen in the lab or anything, so something to keep monitoring."

I will continue to monitor progress on the new component. When we have time, it will be worth looking into how we can re-design the feedback loop taking in suggestions from GDS regarding the use of buttons for accessibility, whilst maintaining minimal visual attention so we don't distract users from the main body content.
