### ISSUE TITLE
OneApp App Store Beta Icon

### ISSUE THREAD

**Issue by samanthabinns** [wmcadigital/wmn-design-system#505]
## What
> Give a brief description of the style, component or pattern you want to propose.
We require a new icon for the Apple and Google Play stores for the Swift App. The icon needs to use the Swift logo but include 'Beta' in the design. From looking at other apps, some have a 'Beta' strip going across the icon which I think works well.

## Why
> Explain why you think this should be added to the West Midlands Network Design System (WMN DS).
We are preparing the Swift OneApp for a beta launch in December. In order to make this clear to customers we need an icon which includes Beta.
> - What evidence do you have that it's needed by multiple services across government? N/A
> - What evidence do you have that it meets the needs of the users of those services? N/A
> - Have you checked that it doesn't already exist in the WMN DS? N/A

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

Is it possible to get this into this sprint?
I have attached assets previously provided by Martin as an example of the different dimensions and file formats needed (see Swift folder).

![image](https://user-images.githubusercontent.com/61703409/100349593-9b52b280-2fe0-11eb-950b-ae0a58fa8e6b.png)
[Swift App Icons.zip](https://github.com/wmcadigital/wmn-design-system/files/5603146/Swift.App.Icons.zip)

**Comment by jkmnch** [comment]
@samanthabinns Hi Sam,

Here is my proposed idea for the Apple App Store icon:

![Screenshot 2020-11-26 at 14 36 37](https://user-images.githubusercontent.com/62507489/100363644-f5f60980-2ff4-11eb-96e7-52daf1d923ce.png)

I've added the border-radius in the right icon to show you what it would look like in the Apple App Store, as Apple adds the border-radius themselves after you upload the icon to the store.

Let me know what you think. Once we agree on an icon, then I'll go ahead and resize the icon for the different resolutions.

**Comment by samanthabinns** [comment]
@jkmnch yes that's perfect! Thank you 👍

**Comment by samanthabinns** [comment]
You have to applaud me for how in touch I am with the guidelines ;)

**Comment by jkmnch** [comment]
@samanthabinns Yes, thank you for sending over the dimensions. I was a little worried at first because I know app icons are more complicated then they seem, but the Sketch file has helped immensely 👍 

However...

For the Android adaptive icons, I have added the 'Beta' banner into the foreground SVG along with the swift icon, so all the different shaped icons should appear like this:

![Screenshot 2020-11-26 at 15 27 18](https://user-images.githubusercontent.com/62507489/100369197-8257fa80-2ffc-11eb-8d3b-800534b72bab.png)

For reference, here are the adaptive icons without the 'Beta' banner:

![Screenshot 2020-11-26 at 15 27 10](https://user-images.githubusercontent.com/62507489/100369237-90a61680-2ffc-11eb-8db4-b7b88e3395ed.png)

I don't have any previous experience of designing Adaptive icons, so I can't guarantee that they'll look as exactly as I've designed them. It might be a case of testing it out and getting back to me with any issues.

I've resized all the Apple App Store icons, so if you're happy with the Android Adaptive icons, then I'll send all of them over.

**Comment by samanthabinns** [comment]
@jkmnch I'm not that familiar with the sizing in the app store myself. So perhaps your right that if you can send over the assets I will let you know if there are issues.

**Comment by jkmnch** [comment]
Morning @samanthabinns 

Here are all the App Store/Play Store icons: 
[Swift App Store:Play Store Icons.zip](https://github.com/wmcadigital/wmn-design-system/files/5606766/Swift.App.Store.Play.Store.Icons.zip)

Let us know if you have any issues with the Android Adaptive icons.

**Comment by samanthabinns** [comment]
@jkmnch I cannot open the files, can you check that they are working okay? I am getting the below message:
![image](https://user-images.githubusercontent.com/61703409/100441528-86d4ef80-309e-11eb-8b19-fb9660f609ee.png)

**Comment by jkmnch** [comment]
@samanthabinns It may be because I had a forward slash in the file name.

Try this file instead: 
[Swift App Store Icons.zip](https://github.com/wmcadigital/wmn-design-system/files/5607450/Swift.App.Store.Icons.zip)

**Comment by samanthabinns** [comment]
@jkmnch nope still not working

**Comment by jkmnch** [comment]
@samanthabinns That's odd, it works fine on my MacBook.

Try this file instead: 
[Swift App Store Icons.zip](https://github.com/wmcadigital/wmn-design-system/files/5607465/Swift.App.Store.Icons.zip)

**Comment by samanthabinns** [comment]
@jkmnch  Bingo! That's fine now, thank you. Will let you know if any issues with uploading.
