### ISSUE TITLE
Documentation for Button as Link

### ISSUE THREAD

**Issue by catiarodriguescosta** [wmcadigital/wmn-design-system#533]
Could you create a text for Button as Link? It is a button with Link appearance to be integrated in the button page component for the design system. :)

## When not to use it?

**Comment by somtmee** [comment]
@catiarodriguescosta sure thing. @mrmjprice - can you share some information on what it does, when to use it and when not to use it? I've checked NHS and GOV service manuals but can't find a similar component

**Comment by mrmjprice** [comment]
Am going to defer the documentation to @KaterinaKir and @jkmnch 

I would just mention a recent [GOV.UK](https://gov.uk) change where they changed the footer feedback loop text links to buttons. This was to meet accessibility regs as they decided the link didn't behave like a link, more like an interface button.

The discussion was in x-gov Slack, so it might be worth asking for any research in the design system channel

**Comment by somtmee** [comment]
Sure thing, I'll ask the question in Slack

________________________________

**Comment by jkmnch** [comment]
## What does it do?
* Behaves the same as a button, but uses the [Link](https://designsystem.wmnetwork.co.uk/components/links/) styling
* Performs an action on the page instead of directing the user to an internal or external page
* Uses the <button> tag for accessibility

## When to use it?
* When a user needs to perform an action on a page
* When there is limited space for a button

## When not to use it?
* The start of a process
* When you want to direct the user to an internal or external page

**Comment by catiarodriguescosta** [comment]
Thank you Jake @jkmnch!

**Comment by houbly** [comment]
This update is now live
